# Generated by Django 4.2 on 2023-05-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
