# Generated by Django 4.2 on 2023-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_salesinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='state',
            field=models.SmallIntegerField(choices=[('待发货', '待发货'), ('代签收', '待签收'), ('待退款', '待退款')], default=0, verbose_name='状态'),
        ),
    ]
