# Generated by Django 4.2 on 2023-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_salesinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='state',
            field=models.CharField(choices=[('待发货', '待发货'), ('待签收', '待签收'), ('待退款', '待退款')], max_length=16, verbose_name='状态'),
        ),
    ]
